/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.empleado;
import com.mycompany.empleado.EmpleadoPermanente;
import com.mycompany.empleado.EmpleadoTemporal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Date;
import java.util.Calendar;
import javax.swing.ImageIcon;
/**
 *
 * @author Angely Nikol
 */
public class DatosEmpleado extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DatosEmpleado.class.getName());

    /**
     * Creates new form DatosEmpleado
     */
    public DatosEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        JCTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Empleado Permanente", "Empleado Temporal" }));

    jPanelDatosEmpleado.setVisible(false);
    
 
    BTNEliminar_Empleado.setEnabled(false);
    TXTBeneficio.setVisible(false);
    LBLBeneficio.setVisible(false);
    LBLFechaFinContrato.setVisible(false);
    LBLHorasTrabajadas.setVisible(false);
    LBLValorHora.setVisible(false);
    JCalendarFinContato.setVisible(false);
    TXTHorasTrabajadas.setVisible(false);
    TXTValorHora.setVisible(false);

    TXTIDEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            verificarCamposParaGuardar();
            verificarCamposParaActualizar();
        }
    });

    TXTNombreEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            verificarCamposParaGuardar();
            verificarCamposParaActualizar();
        }
    });

    TXTApellidoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            verificarCamposParaGuardar();
            verificarCamposParaActualizar();
        }
    });

    TXTSalario.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            verificarCamposParaGuardar();
            verificarCamposParaActualizar();
        }
    });

    TXTBeneficio.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            verificarCamposParaGuardar();
            verificarCamposParaActualizar();
        }
    });

    TXTHorasTrabajadas.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            verificarCamposParaGuardar();
            verificarCamposParaActualizar();
        }
    });

    TXTValorHora.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            verificarCamposParaGuardar();
            verificarCamposParaActualizar();
        }
    });
    
    JCTipoEmpleado.addActionListener(new java.awt.event.ActionListener() {
    @Override
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        verificarCamposParaActualizar();
    }
});
  

    }public void limpiarCampos(){

    TXTIDEmpleado.setText("");
    TXTNombreEmpleado.setText("");
    TXTApellidoEmpleado.setText("");
    TXTSalario.setText("");
    TXTBeneficio.setText("");
    JCalendarFinContato.setDate(null);
    TXTHorasTrabajadas.setText("");
    TXTValorHora.setText("");
    
    }
    ArrayList<EmpleadoPermanente> empleadoP = new ArrayList<>();
    ArrayList<EmpleadoTemporal> empleadoT = new ArrayList<>();
    ArrayList<Departamento> departamentos = new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGesionEmpleado = new javax.swing.JPanel();
        LBLGestiondeEmpleados = new javax.swing.JLabel();
        jPanelAccionEmpleado = new javax.swing.JPanel();
        BTNCrearEmpleado = new javax.swing.JButton();
        BTNActualizarEmpleado = new javax.swing.JButton();
        BTNElminarEmpleado = new javax.swing.JButton();
        jPanelDatosEmpleado = new javax.swing.JPanel();
        LBLDatosEmpleado = new javax.swing.JLabel();
        LBLIDEmpleado = new javax.swing.JLabel();
        LBLNombreEmpleado = new javax.swing.JLabel();
        LBLApellidoEmpleado = new javax.swing.JLabel();
        LBLFechaInicioContrato = new javax.swing.JLabel();
        LBLSalario = new javax.swing.JLabel();
        LBLTipoEmpleado = new javax.swing.JLabel();
        TXTIDEmpleado = new javax.swing.JTextField();
        TXTNombreEmpleado = new javax.swing.JTextField();
        TXTApellidoEmpleado = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        TXTSalario = new javax.swing.JTextField();
        JCTipoEmpleado = new javax.swing.JComboBox<>();
        LBLBeneficio = new javax.swing.JLabel();
        LBLFechaFinContrato = new javax.swing.JLabel();
        LBLHorasTrabajadas = new javax.swing.JLabel();
        LBLValorHora = new javax.swing.JLabel();
        TXTBeneficio = new javax.swing.JTextField();
        TXTHorasTrabajadas = new javax.swing.JTextField();
        TXTValorHora = new javax.swing.JTextField();
        JCalendarFinContato = new com.toedter.calendar.JDateChooser();
        BTNGuardarEmpleado = new javax.swing.JButton();
        BTNActualizar_Empleado = new javax.swing.JButton();
        BTNEliminar_Empleado = new javax.swing.JButton();
        BTNBuscar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LBLGestiondeEmpleados.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        LBLGestiondeEmpleados.setText("Gestion de Empleados");

        javax.swing.GroupLayout jPanelGesionEmpleadoLayout = new javax.swing.GroupLayout(jPanelGesionEmpleado);
        jPanelGesionEmpleado.setLayout(jPanelGesionEmpleadoLayout);
        jPanelGesionEmpleadoLayout.setHorizontalGroup(
            jPanelGesionEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGesionEmpleadoLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(LBLGestiondeEmpleados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGesionEmpleadoLayout.setVerticalGroup(
            jPanelGesionEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGesionEmpleadoLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(LBLGestiondeEmpleados)
                .addGap(17, 17, 17))
        );

        BTNCrearEmpleado.setText("Crear Empleado");
        BTNCrearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCrearEmpleadoActionPerformed(evt);
            }
        });

        BTNActualizarEmpleado.setText("Actualizar Empleado");
        BTNActualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNActualizarEmpleadoActionPerformed(evt);
            }
        });

        BTNElminarEmpleado.setText("Eliminar Empleado");
        BTNElminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNElminarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAccionEmpleadoLayout = new javax.swing.GroupLayout(jPanelAccionEmpleado);
        jPanelAccionEmpleado.setLayout(jPanelAccionEmpleadoLayout);
        jPanelAccionEmpleadoLayout.setHorizontalGroup(
            jPanelAccionEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccionEmpleadoLayout.createSequentialGroup()
                .addGroup(jPanelAccionEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNActualizarEmpleado)
                    .addGroup(jPanelAccionEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAccionEmpleadoLayout.createSequentialGroup()
                            .addGap(222, 222, 222)
                            .addComponent(BTNElminarEmpleado))
                        .addGroup(jPanelAccionEmpleadoLayout.createSequentialGroup()
                            .addGap(225, 225, 225)
                            .addComponent(BTNCrearEmpleado))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAccionEmpleadoLayout.setVerticalGroup(
            jPanelAccionEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccionEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNCrearEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNActualizarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNElminarEmpleado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LBLDatosEmpleado.setText("Datos Empleado");

        LBLIDEmpleado.setText("ID Empleado");

        LBLNombreEmpleado.setText("Nombre Empledo");

        LBLApellidoEmpleado.setText("Apellido Empleado");

        LBLFechaInicioContrato.setText("Fecha Inicio Contrato");

        LBLSalario.setText("Salario");

        LBLTipoEmpleado.setText("Tipo Empleado");

        TXTIDEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTIDEmpleadoActionPerformed(evt);
            }
        });

        TXTNombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNombreEmpleadoActionPerformed(evt);
            }
        });

        TXTApellidoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTApellidoEmpleadoActionPerformed(evt);
            }
        });

        TXTSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTSalarioActionPerformed(evt);
            }
        });

        JCTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado Permanente", "Empleado Temporal" }));
        JCTipoEmpleado.setToolTipText("");
        JCTipoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCTipoEmpleadoActionPerformed(evt);
            }
        });

        LBLBeneficio.setText("Beneficio");

        LBLFechaFinContrato.setText("Fecha Fin Contrato");

        LBLHorasTrabajadas.setText("Horas Trabajadas");

        LBLValorHora.setText("Valor Hora");

        TXTBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTBeneficioActionPerformed(evt);
            }
        });

        TXTHorasTrabajadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTHorasTrabajadasActionPerformed(evt);
            }
        });

        TXTValorHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTValorHoraActionPerformed(evt);
            }
        });

        BTNGuardarEmpleado.setText("Guardar");
        BTNGuardarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGuardarEmpleadoActionPerformed(evt);
            }
        });

        BTNActualizar_Empleado.setText("Actualizar ");
        BTNActualizar_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNActualizar_EmpleadoActionPerformed(evt);
            }
        });

        BTNEliminar_Empleado.setText("Eliminar");
        BTNEliminar_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminar_EmpleadoActionPerformed(evt);
            }
        });

        BTNBuscar2.setText("Buscar2");
        BTNBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosEmpleadoLayout = new javax.swing.GroupLayout(jPanelDatosEmpleado);
        jPanelDatosEmpleado.setLayout(jPanelDatosEmpleadoLayout);
        jPanelDatosEmpleadoLayout.setHorizontalGroup(
            jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                                .addComponent(LBLFechaFinContrato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JCalendarFinContato, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                                .addComponent(LBLHorasTrabajadas)
                                .addGap(18, 18, 18)
                                .addComponent(TXTHorasTrabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(LBLBeneficio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosEmpleadoLayout.createSequentialGroup()
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                                    .addComponent(LBLTipoEmpleado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JCTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                                    .addComponent(LBLApellidoEmpleado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TXTApellidoEmpleado))
                                .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                                    .addComponent(LBLSalario)
                                    .addGap(18, 18, 18)
                                    .addComponent(TXTSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                                    .addComponent(LBLNombreEmpleado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TXTNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                                    .addComponent(LBLIDEmpleado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TXTIDEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(LBLDatosEmpleado))
                            .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                                .addComponent(LBLFechaInicioContrato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(LBLValorHora)
                        .addGap(30, 30, 30)
                        .addComponent(TXTValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNActualizar_Empleado)
                    .addComponent(BTNGuardarEmpleado)
                    .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BTNEliminar_Empleado)
                        .addComponent(BTNBuscar2)))
                .addGap(134, 134, 134))
        );
        jPanelDatosEmpleadoLayout.setVerticalGroup(
            jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBLDatosEmpleado)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLIDEmpleado)
                            .addComponent(TXTIDEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLNombreEmpleado)
                            .addComponent(TXTNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLApellidoEmpleado)
                            .addComponent(TXTApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLFechaInicioContrato)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(BTNGuardarEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNActualizar_Empleado)
                        .addGap(18, 18, 18)
                        .addComponent(BTNEliminar_Empleado)))
                .addGap(9, 9, 9)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLSalario)
                    .addComponent(TXTSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JCalendarFinContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                        .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLTipoEmpleado)
                            .addComponent(JCTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNBuscar2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLBeneficio)
                            .addComponent(TXTBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(LBLFechaFinContrato)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosEmpleadoLayout.createSequentialGroup()
                        .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLHorasTrabajadas)
                            .addComponent(TXTHorasTrabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(LBLValorHora))
                    .addComponent(TXTValorHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGesionEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAccionEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDatosEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGesionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCrearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCrearEmpleadoActionPerformed
       limpiarCampos();
    jPanelDatosEmpleado.setVisible(true);

    BTNGuardarEmpleado.setVisible(true);
    BTNGuardarEmpleado.setEnabled(false);

    BTNActualizar_Empleado.setVisible(false);
    BTNEliminar_Empleado.setVisible(false);
    BTNBuscar2.setVisible(false);

    // Mostrar todos los campos para crear
    LBLIDEmpleado.setVisible(true);
    TXTIDEmpleado.setVisible(true);
    LBLNombreEmpleado.setVisible(true);
    TXTNombreEmpleado.setVisible(true);
    LBLApellidoEmpleado.setVisible(true);
    TXTApellidoEmpleado.setVisible(true);
    LBLFechaInicioContrato.setVisible(true);
    jDateChooser1.setVisible(true);
    LBLSalario.setVisible(true);
    TXTSalario.setVisible(true);
    LBLTipoEmpleado.setVisible(true);
    JCTipoEmpleado.setVisible(true);
    LBLBeneficio.setVisible(true);
    TXTBeneficio.setVisible(true);
    LBLFechaFinContrato.setVisible(true);
    JCalendarFinContato.setVisible(true);
    LBLHorasTrabajadas.setVisible(true);
    TXTHorasTrabajadas.setVisible(true);
    LBLValorHora.setVisible(true);
    TXTValorHora.setVisible(true);

    }//GEN-LAST:event_BTNCrearEmpleadoActionPerformed

    private void JCTipoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCTipoEmpleadoActionPerformed
                                              
    String seleccion = (String) JCTipoEmpleado.getSelectedItem();

    if ("Empleado Permanente".equals(seleccion)) {
        // Mostrar solo beneficio
        TXTBeneficio.setVisible(true);
        LBLBeneficio.setVisible(true);

       
        LBLFechaFinContrato.setVisible(false);
        JCalendarFinContato.setVisible(false);
        LBLHorasTrabajadas.setVisible(false);
        TXTHorasTrabajadas.setVisible(false);
        LBLValorHora.setVisible(false);
        TXTValorHora.setVisible(false);

    } else if ("Empleado Temporal".equals(seleccion)) {

        LBLFechaFinContrato.setVisible(true);
        JCalendarFinContato.setVisible(true);
        LBLHorasTrabajadas.setVisible(true);
        TXTHorasTrabajadas.setVisible(true);
        LBLValorHora.setVisible(true);
        TXTValorHora.setVisible(true);


        TXTBeneficio.setVisible(false);
        LBLBeneficio.setVisible(false);

    } else {
       
        TXTBeneficio.setVisible(false);
        LBLBeneficio.setVisible(false);
        LBLFechaFinContrato.setVisible(false);
        JCalendarFinContato.setVisible(false);
        LBLHorasTrabajadas.setVisible(false);
        TXTHorasTrabajadas.setVisible(false);
        LBLValorHora.setVisible(false);
        TXTValorHora.setVisible(false);
    }

       // TODO add your handling code here:
    }//GEN-LAST:event_JCTipoEmpleadoActionPerformed

    private void BTNGuardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGuardarEmpleadoActionPerformed
       try {
        int id = Integer.parseInt(TXTIDEmpleado.getText());
        String nombre = TXTNombreEmpleado.getText();
        String apellido = TXTApellidoEmpleado.getText();
        double salario = Double.parseDouble(TXTSalario.getText());
        Date fechaInicio = jDateChooser1.getDate(); // fecha inicio contrato

        String tipo = (String) JCTipoEmpleado.getSelectedItem();

        if (tipo.equals("Empleado Permanente")) {
            String beneficio = TXTBeneficio.getText();

            EmpleadoPermanente emp = new EmpleadoPermanente(
                    id, nombre, apellido, fechaInicio, salario, beneficio);

            empleadoP.add(emp);
            javax.swing.JOptionPane.showMessageDialog(this, "Empleado permanente guardado");
        } else {
            Date fechaFin = JCalendarFinContato.getDate();
            int horas = Integer.parseInt(TXTHorasTrabajadas.getText());
            double valorHora = Double.parseDouble(TXTValorHora.getText());

            EmpleadoTemporal emp = new EmpleadoTemporal(
                    id, nombre, apellido, fechaInicio, salario, fechaFin, horas, valorHora);

            empleadoT.add(emp);
            javax.swing.JOptionPane.showMessageDialog(this, "Empleado temporal guardado");
        }

        // Limpiar campos y deshabilitar el botón hasta nuevo registro
        limpiarCampos();
        BTNGuardarEmpleado.setEnabled(false);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
    }

// TODO add your handling code here:
    }//GEN-LAST:event_BTNGuardarEmpleadoActionPerformed
private void verificarCamposParaGuardar() {
    boolean completos = !TXTIDEmpleado.getText().isEmpty() &&
                        !TXTNombreEmpleado.getText().isEmpty() &&
                        !TXTApellidoEmpleado.getText().isEmpty() &&
                        !TXTSalario.getText().isEmpty();

 
    if (JCTipoEmpleado.getSelectedItem().equals("Empleado Permanente")) {
        completos = completos && !TXTBeneficio.getText().isEmpty();
    }


    if (JCTipoEmpleado.getSelectedItem().equals("Empleado Temporal")) {
        completos = completos && JCalendarFinContato.getDate() != null &&
                    !TXTHorasTrabajadas.getText().isEmpty() &&
                    !TXTValorHora.getText().isEmpty();
    }

    BTNGuardarEmpleado.setEnabled(completos);
}
    private void BTNActualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNActualizarEmpleadoActionPerformed
     limpiarCampos();
    jPanelDatosEmpleado.setVisible(true);

    BTNGuardarEmpleado.setVisible(false);
    BTNActualizar_Empleado.setVisible(true);
    BTNActualizar_Empleado.setEnabled(false); 
    BTNEliminar_Empleado.setVisible(false);
 
    BTNBuscar2.setVisible(true);
    
    LBLIDEmpleado.setVisible(true);
    TXTIDEmpleado.setVisible(true);

    LBLNombreEmpleado.setVisible(false);
    TXTNombreEmpleado.setVisible(false);
    LBLApellidoEmpleado.setVisible(false);
    TXTApellidoEmpleado.setVisible(false);
    LBLFechaInicioContrato.setVisible(false);
    jDateChooser1.setVisible(false);
    LBLSalario.setVisible(false);
    TXTSalario.setVisible(false);
    LBLTipoEmpleado.setVisible(false);
    JCTipoEmpleado.setVisible(false);
    LBLBeneficio.setVisible(false);
    TXTBeneficio.setVisible(false);
    LBLFechaFinContrato.setVisible(false);
    JCalendarFinContato.setVisible(false);
    LBLHorasTrabajadas.setVisible(false);
    TXTHorasTrabajadas.setVisible(false);
    LBLValorHora.setVisible(false);
    TXTValorHora.setVisible(false);
    }//GEN-LAST:event_BTNActualizarEmpleadoActionPerformed

    private void BTNActualizar_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNActualizar_EmpleadoActionPerformed
                                                     
    try {
        int id = Integer.parseInt(TXTIDEmpleado.getText());
        String nombre = TXTNombreEmpleado.getText();
        String apellido = TXTApellidoEmpleado.getText();
        double salario = Double.parseDouble(TXTSalario.getText());
        String tipo = (String) JCTipoEmpleado.getSelectedItem();

     
        for (EmpleadoPermanente emp : empleadoP) {
            if (emp.getIdEmpleado() == id) {
                emp.setNombre(nombre);
                emp.setApellido(apellido);
                emp.setSalario(salario);

                if ("Empleado Permanente".equals(tipo)) {
                    emp.setBeneficio(TXTBeneficio.getText());
                } else {
               
                    empleadoP.remove(emp);
                    EmpleadoTemporal nuevo = new EmpleadoTemporal(
                        id,
                        nombre,
                        apellido,
                        jDateChooser1.getDate(), 
                        salario,
                        JCalendarFinContato.getDate(), 
                        Integer.parseInt(TXTHorasTrabajadas.getText()),
                        Double.parseDouble(TXTValorHora.getText())
                    );
                    empleadoT.add(nuevo);
                }

                javax.swing.JOptionPane.showMessageDialog(this, "Empleado actualizado");
                return;
            }
        }

   
        for (EmpleadoTemporal emp : empleadoT) {
            if (emp.getIdEmpleado() == id) {
                emp.setNombre(nombre);
                emp.setApellido(apellido);
                emp.setSalario(salario);

                if ("Empleado Temporal".equals(tipo)) {
                    emp.setFechaInicioContrato(jDateChooser1.getDate());
                    emp.setFechaFinContrato(JCalendarFinContato.getDate());
                    emp.setHorasTrabajadas(Integer.parseInt(TXTHorasTrabajadas.getText()));
                    emp.setValorHora(Double.parseDouble(TXTValorHora.getText()));
                } else {
                    
                    empleadoT.remove(emp);
               EmpleadoPermanente nuevo = new EmpleadoPermanente(
                 id,
                 nombre,
                 apellido,
                 jDateChooser1.getDate(), 
                 salario,
                 TXTBeneficio.getText()
);

                javax.swing.JOptionPane.showMessageDialog(this, "Empleado actualizado");
                return;
            }
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, "Empleado no encontrado");
        
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar empleado: " + e.getMessage());
    }

    }//GEN-LAST:event_BTNActualizar_EmpleadoActionPerformed

    private void BTNElminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNElminarEmpleadoActionPerformed
    limpiarCampos();
    jPanelDatosEmpleado.setVisible(true);

    BTNGuardarEmpleado.setVisible(false);
    BTNActualizar_Empleado.setVisible(false);
    BTNEliminar_Empleado.setVisible(true);
    BTNEliminar_Empleado.setEnabled(false); 
    BTNBuscar2.setVisible(true);
  
    LBLIDEmpleado.setVisible(true);
    TXTIDEmpleado.setVisible(true);

  
    LBLNombreEmpleado.setVisible(false);
    TXTNombreEmpleado.setVisible(false);
    LBLApellidoEmpleado.setVisible(false);
    TXTApellidoEmpleado.setVisible(false);
    LBLFechaInicioContrato.setVisible(false);
    jDateChooser1.setVisible(false);
    LBLSalario.setVisible(false);
    TXTSalario.setVisible(false);
    LBLTipoEmpleado.setVisible(false);
    JCTipoEmpleado.setVisible(false);
    LBLBeneficio.setVisible(false);
    TXTBeneficio.setVisible(false);
    LBLFechaFinContrato.setVisible(false);
    JCalendarFinContato.setVisible(false);
    LBLHorasTrabajadas.setVisible(false);
    TXTHorasTrabajadas.setVisible(false);
    LBLValorHora.setVisible(false);
    TXTValorHora.setVisible(false);
                                                  
    int id = Integer.parseInt(TXTIDEmpleado.getText());

    for (EmpleadoPermanente emp : empleadoP) {
        if (emp.getIdEmpleado() == id) {
            empleadoP.remove(emp);
            javax.swing.JOptionPane.showMessageDialog(this, "Empleado permanente eliminado");
            limpiarCampos();
            return;
        }
    }

    for (EmpleadoTemporal emp : empleadoT) {
        if (emp.getIdEmpleado() == id) {
            empleadoT.remove(emp);
            javax.swing.JOptionPane.showMessageDialog(this, "Empleado temporal eliminado");
            limpiarCampos();
            return;
        }
    }

    javax.swing.JOptionPane.showMessageDialog(this, "Empleado no encontrado");
// TODO add your handling code here:
    }//GEN-LAST:event_BTNElminarEmpleadoActionPerformed

    private void BTNEliminar_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliminar_EmpleadoActionPerformed
                                                   
    try {
        int id = Integer.parseInt(TXTIDEmpleado.getText());

        boolean eliminado = false;

        // Eliminar de permanentes
        if (empleadoP.removeIf(emp -> emp.getIdEmpleado() == id)) {
            eliminado = true;
        }

        // Eliminar de temporales
        if (empleadoT.removeIf(emp -> emp.getIdEmpleado() == id)) {
            eliminado = true;
        }

        if (eliminado) {
            javax.swing.JOptionPane.showMessageDialog(this, "Empleado eliminado correctamente");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el empleado para eliminar");
        }

        limpiarCampos();
        BTNEliminar_Empleado.setEnabled(false);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar empleado: " + e.getMessage());
    }

     // TODO add your handling code here:
    }//GEN-LAST:event_BTNEliminar_EmpleadoActionPerformed

    private void TXTIDEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTIDEmpleadoActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_TXTIDEmpleadoActionPerformed

    private void TXTNombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNombreEmpleadoActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_TXTNombreEmpleadoActionPerformed

    private void TXTApellidoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTApellidoEmpleadoActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_TXTApellidoEmpleadoActionPerformed

    private void TXTSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTSalarioActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_TXTSalarioActionPerformed

    private void TXTBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTBeneficioActionPerformed
   // TODO add your handling code here:
    }//GEN-LAST:event_TXTBeneficioActionPerformed

    private void TXTHorasTrabajadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTHorasTrabajadasActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_TXTHorasTrabajadasActionPerformed

    private void TXTValorHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTValorHoraActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_TXTValorHoraActionPerformed

    private void BTNBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscar2ActionPerformed
 if (BTNActualizarEmpleado.isVisible()) {
        buscarEmpleadoPorID();
        
        BTNActualizar_Empleado.setEnabled(true);
            return;
    } else if (BTNElminarEmpleado.isVisible()) {
        buscarEmpleadoParaEliminar();
        BTNActualizar_Empleado.setEnabled(true);
            return;
    }         // TODO add your handling code here:
    }//GEN-LAST:event_BTNBuscar2ActionPerformed
    private void buscarEmpleadoParaEliminar() {
    int id = Integer.parseInt(TXTIDEmpleado.getText());

    for (EmpleadoPermanente emp : empleadoP) {
        if (emp.getIdEmpleado() == id) {
            mostrarCamposEmpleadoSoloLectura();
            TXTNombreEmpleado.setText(emp.getNombre());
            TXTApellidoEmpleado.setText(emp.getApellido());
            TXTSalario.setText(String.valueOf(emp.getSalario()));
            JCTipoEmpleado.setSelectedItem("Empleado Permanente");
            TXTBeneficio.setText(emp.getBeneficio());
            BTNActualizar_Empleado.setEnabled(true);
            return;
        }
    }

    for (EmpleadoTemporal emp : empleadoT) {
        if (emp.getIdEmpleado() == id) {
            mostrarCamposEmpleadoSoloLectura();
            TXTNombreEmpleado.setText(emp.getNombre());
            TXTApellidoEmpleado.setText(emp.getApellido());
            TXTSalario.setText(String.valueOf(emp.getSalario()));
            JCTipoEmpleado.setSelectedItem("Empleado Temporal");
            JCalendarFinContato.setDate(emp.getFechaFinContrato());
            TXTHorasTrabajadas.setText(String.valueOf(emp.getHorasTrabajadas()));
            TXTValorHora.setText(String.valueOf(emp.getValorHora()));
            BTNActualizar_Empleado.setEnabled(true);
            BTNActualizar_Empleado.setEnabled(true);
            return;
        }
    }

    javax.swing.JOptionPane.showMessageDialog(this, "Empleado no encontrado");
}
    private void mostrarCamposEmpleadoSoloLectura() {
    LBLNombreEmpleado.setVisible(true);
    TXTNombreEmpleado.setVisible(true);
    TXTNombreEmpleado.setEditable(false);

    LBLApellidoEmpleado.setVisible(true);
    TXTApellidoEmpleado.setVisible(true);
    TXTApellidoEmpleado.setEditable(false);

    LBLFechaInicioContrato.setVisible(true);
    jDateChooser1.setVisible(true);
    jDateChooser1.setEnabled(false);

    LBLSalario.setVisible(true);
    TXTSalario.setVisible(true);
    TXTSalario.setEditable(false);

    LBLTipoEmpleado.setVisible(true);
    JCTipoEmpleado.setVisible(true);
    JCTipoEmpleado.setEnabled(false);

    LBLBeneficio.setVisible(true);
    TXTBeneficio.setVisible(true);
    TXTBeneficio.setEditable(false);

    LBLFechaFinContrato.setVisible(true);
    JCalendarFinContato.setVisible(true);
    JCalendarFinContato.setEnabled(false);

    LBLHorasTrabajadas.setVisible(true);
    TXTHorasTrabajadas.setVisible(true);
    TXTHorasTrabajadas.setEditable(false);

    LBLValorHora.setVisible(true);
    TXTValorHora.setVisible(true);
    TXTValorHora.setEditable(false);
}
    private void buscarEmpleadoPorID() {
    int id = Integer.parseInt(TXTIDEmpleado.getText());

    
    for (EmpleadoPermanente emp : empleadoP) {
        if (emp.getIdEmpleado() == id) {
            
            mostrarCamposEmpleado();
            
            TXTNombreEmpleado.setText(emp.getNombre());
            TXTApellidoEmpleado.setText(emp.getApellido());
            TXTSalario.setText(String.valueOf((char) emp.getSalario()));
            JCTipoEmpleado.setSelectedItem("Empleado Permanente");
            TXTBeneficio.setText(emp.getBeneficio());
            return;
        }
    }

   
    for (EmpleadoTemporal emp : empleadoT) {
        if (emp.getIdEmpleado() == id) {
            mostrarCamposEmpleado();
            TXTNombreEmpleado.setText(emp.getNombre());
            TXTApellidoEmpleado.setText(emp.getApellido());
            TXTSalario.setText(String.valueOf(emp.getSalario()));
            JCTipoEmpleado.setSelectedItem("Empleado Temporal");
            JCalendarFinContato.setDate(emp.getFechaFinContrato());
            TXTHorasTrabajadas.setText(String.valueOf(emp.getHorasTrabajadas()));
            TXTValorHora.setText(String.valueOf(emp.getValorHora()));
            return;
        }
    }

    javax.swing.JOptionPane.showMessageDialog(this, "Empleado no encontrado");
}
private void mostrarCamposEmpleado() {
    LBLNombreEmpleado.setVisible(true);
    TXTNombreEmpleado.setVisible(true);
    LBLApellidoEmpleado.setVisible(true);
    TXTApellidoEmpleado.setVisible(true);
    LBLFechaInicioContrato.setVisible(true);
    jDateChooser1.setVisible(true);
    LBLSalario.setVisible(true);
    TXTSalario.setVisible(true);
    LBLTipoEmpleado.setVisible(true);
    JCTipoEmpleado.setVisible(true);
}
private void verificarCamposParaActualizar() {
    boolean completos = !TXTIDEmpleado.getText().isEmpty() &&
                        !TXTNombreEmpleado.getText().isEmpty() &&
                        !TXTApellidoEmpleado.getText().isEmpty() &&
                        !TXTSalario.getText().isEmpty();

    if (JCTipoEmpleado.getSelectedItem().equals("Empleado Permanente")) {
        completos = completos && !TXTBeneficio.getText().isEmpty();
    }

    if (JCTipoEmpleado.getSelectedItem().equals("Empleado Temporal")) {
        completos = completos && JCalendarFinContato.getDate() != null &&
                    !TXTHorasTrabajadas.getText().isEmpty() &&
                    !TXTValorHora.getText().isEmpty();
        
    }
 BTNActualizar_Empleado.setEnabled(completos);
 BTNEliminar_Empleado.setEnabled(true);
}

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNActualizarEmpleado;
    private javax.swing.JButton BTNActualizar_Empleado;
    private javax.swing.JButton BTNBuscar2;
    private javax.swing.JButton BTNCrearEmpleado;
    private javax.swing.JButton BTNEliminar_Empleado;
    private javax.swing.JButton BTNElminarEmpleado;
    private javax.swing.JButton BTNGuardarEmpleado;
    private javax.swing.JComboBox<String> JCTipoEmpleado;
    private com.toedter.calendar.JDateChooser JCalendarFinContato;
    private javax.swing.JLabel LBLApellidoEmpleado;
    private javax.swing.JLabel LBLBeneficio;
    private javax.swing.JLabel LBLDatosEmpleado;
    private javax.swing.JLabel LBLFechaFinContrato;
    private javax.swing.JLabel LBLFechaInicioContrato;
    private javax.swing.JLabel LBLGestiondeEmpleados;
    private javax.swing.JLabel LBLHorasTrabajadas;
    private javax.swing.JLabel LBLIDEmpleado;
    private javax.swing.JLabel LBLNombreEmpleado;
    private javax.swing.JLabel LBLSalario;
    private javax.swing.JLabel LBLTipoEmpleado;
    private javax.swing.JLabel LBLValorHora;
    private javax.swing.JTextField TXTApellidoEmpleado;
    private javax.swing.JTextField TXTBeneficio;
    private javax.swing.JTextField TXTHorasTrabajadas;
    private javax.swing.JTextField TXTIDEmpleado;
    private javax.swing.JTextField TXTNombreEmpleado;
    private javax.swing.JTextField TXTSalario;
    private javax.swing.JTextField TXTValorHora;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanelAccionEmpleado;
    private javax.swing.JPanel jPanelDatosEmpleado;
    private javax.swing.JPanel jPanelGesionEmpleado;
    // End of variables declaration//GEN-END:variables
}
