/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.empleado;

import com.mycompany.empleado.EmpleadoPermanente;
import com.mycompany.empleado.EmpleadoTemporal;
import java.util.ArrayList;
import java.util.Date;
import com.mycompany.empleado.ReporteDesempeño;
import java.util.Calendar;
import javax.swing.ImageIcon;
import java.util.ArrayList;
/**
 *
 * @author Angely Nikol
 */
public class GestionDepartamentos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionDepartamentos.class.getName());
       private ArrayList<Departamento> departamentos = new ArrayList<>();
      
       Departamento depRH = new Departamento(1, "Recursos Humanos", 2000);




    /**
     * Creates new form GestionDepartamentos
     */
    public GestionDepartamentos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.setLocationRelativeTo(null);
   
        Departamento depRH = new Departamento(1, "Recursos Humanos", 2000);
        departamentos.add(depRH);


        EmpleadoPermanente nuevoEmpleado = new EmpleadoPermanente(
            101, "Ana", "Gómez", new Date(), 1500, "Seguro"
        );
        depRH.agregarEmpleado(nuevoEmpleado);
    BTNGuardarDepartamento.setVisible(false);
    BTNGuardarDepartamento.setEnabled(false);
    TXTIDDepartamento.setVisible(false);
    LBLIDDepartmento.setVisible(false); 
    TXTNombreDepartamento.setVisible(false);
    TXTSalarioBase.setVisible(false);
    
    BTNActualizar_Departamento.setVisible(false);
    BTNEliminar_Departamento.setVisible(false);
    
    LBLDatosDepartamento.setVisible(false);
    LBLIDDepartmento.setVisible(false);
    LBLNombre.setVisible(false);
    LBLSalarioBase.setVisible(false);
    BTNBuscarDepartamento.setVisible(false);
        TXTIDDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            verificarCamposDepartamento();
        }
    });

    TXTNombreDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            verificarCamposDepartamento();
        }
    });

    TXTSalarioBase.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            verificarCamposDepartamento();
        }
    });
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BTNCrearDepartamento = new javax.swing.JButton();
        BTNActualizarDepartamento = new javax.swing.JButton();
        BTNEliminarDepartamento = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        LBLDatosDepartamento = new javax.swing.JLabel();
        LBLNombre = new javax.swing.JLabel();
        LBLSalarioBase = new javax.swing.JLabel();
        BTNGuardarDepartamento = new javax.swing.JButton();
        BTNActualizar_Departamento = new javax.swing.JButton();
        BTNEliminar_Departamento = new javax.swing.JButton();
        TXTIDDepartamento = new javax.swing.JTextField();
        TXTNombreDepartamento = new javax.swing.JTextField();
        TXTSalarioBase = new javax.swing.JTextField();
        LBLIDDepartmento = new javax.swing.JLabel();
        BTNBuscarDepartamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 2, 24)); // NOI18N
        jLabel2.setText("Gestion de Departamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        BTNCrearDepartamento.setText("Crear Departamento");
        BTNCrearDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCrearDepartamentoActionPerformed(evt);
            }
        });

        BTNActualizarDepartamento.setText("Actualizar Departamento");
        BTNActualizarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNActualizarDepartamentoActionPerformed(evt);
            }
        });

        BTNEliminarDepartamento.setText("Eliminar Departamento");
        BTNEliminarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminarDepartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNActualizarDepartamento)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BTNEliminarDepartamento)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(BTNCrearDepartamento)
                            .addGap(7, 7, 7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(BTNCrearDepartamento)
                .addGap(21, 21, 21)
                .addComponent(BTNActualizarDepartamento)
                .addGap(18, 18, 18)
                .addComponent(BTNEliminarDepartamento)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        LBLDatosDepartamento.setText("Datos Departamento");

        LBLNombre.setText("Nombre");

        LBLSalarioBase.setText("Salario Base");

        BTNGuardarDepartamento.setText("Guardar ");
        BTNGuardarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGuardarDepartamentoActionPerformed(evt);
            }
        });

        BTNActualizar_Departamento.setText("Actulizar");
        BTNActualizar_Departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNActualizar_DepartamentoActionPerformed(evt);
            }
        });

        BTNEliminar_Departamento.setText("Elimiar");
        BTNEliminar_Departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminar_DepartamentoActionPerformed(evt);
            }
        });

        TXTNombreDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNombreDepartamentoActionPerformed(evt);
            }
        });

        LBLIDDepartmento.setText("ID Departamento");

        BTNBuscarDepartamento.setText("Buscar");
        BTNBuscarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarDepartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(LBLDatosDepartamento))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LBLIDDepartmento)
                            .addComponent(LBLNombre)
                            .addComponent(LBLSalarioBase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTNombreDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTIDDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNActualizar_Departamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNGuardarDepartamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNEliminar_Departamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNBuscarDepartamento, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLDatosDepartamento)
                    .addComponent(BTNGuardarDepartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNActualizar_Departamento)
                    .addComponent(LBLIDDepartmento)
                    .addComponent(TXTIDDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNEliminar_Departamento)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTNombreDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LBLNombre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TXTSalarioBase, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLSalarioBase)
                            .addComponent(BTNBuscarDepartamento))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTNombreDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNombreDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNombreDepartamentoActionPerformed

    private void BTNGuardarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGuardarDepartamentoActionPerformed
try {
        int id = Integer.parseInt(TXTIDDepartamento.getText());
        String nombre = TXTNombreDepartamento.getText();
        double salarioBase = Double.parseDouble(TXTSalarioBase.getText());

        Departamento depto = new Departamento(id, nombre, salarioBase);
        departamentos.add(depto);

        javax.swing.JOptionPane.showMessageDialog(this, "Departamento guardado");

        limpiarCamposDepartamento();
        BTNGuardarDepartamento.setEnabled(false);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar departamento: " + e.getMessage());
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_BTNGuardarDepartamentoActionPerformed

    private void BTNCrearDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCrearDepartamentoActionPerformed
    limpiarCamposDepartamento();
    jPanel3.setVisible(true); 

    LBLNombre.setVisible(true);
    BTNGuardarDepartamento.setVisible(true);
    BTNGuardarDepartamento.setEnabled(false);
    TXTIDDepartamento.setVisible(true);
    LBLIDDepartmento.setVisible(true); 
    TXTNombreDepartamento.setVisible(true);
    TXTSalarioBase.setVisible(true);
    LBLSalarioBase.setVisible(true);
    
    BTNActualizar_Departamento.setVisible(false);
    BTNEliminar_Departamento.setVisible(false);
    
    BTNBuscarDepartamento.setVisible(false);
  
    }//GEN-LAST:event_BTNCrearDepartamentoActionPerformed

    private void BTNActualizarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNActualizarDepartamentoActionPerformed
limpiarCamposDepartamento();
    jPanel3.setVisible(true);

    TXTIDDepartamento.setVisible(true);
    LBLIDDepartmento.setVisible(true); 

    TXTNombreDepartamento.setVisible(false);
    TXTSalarioBase.setVisible(false);
    LBLNombre.setVisible(false);
    LBLSalarioBase.setVisible(false);

    BTNActualizar_Departamento.setVisible(true);
    BTNActualizar_Departamento.setEnabled(false);

    BTNGuardarDepartamento.setVisible(false);
    BTNEliminar_Departamento.setVisible(false);

    BTNBuscarDepartamento.setVisible(true);
     // TODO add your handling code here:
    }//GEN-LAST:event_BTNActualizarDepartamentoActionPerformed

    private void BTNActualizar_DepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNActualizar_DepartamentoActionPerformed
     try {
        int id = Integer.parseInt(TXTIDDepartamento.getText());
        String nombre = TXTNombreDepartamento.getText();
        double salarioBase = Double.parseDouble(TXTSalarioBase.getText());

        for (Departamento depto : departamentos) {
            if (depto.getIdDepartamento() == id) {
                depto.setNombre(nombre);
                depto.setSalarioBase(salarioBase);

                javax.swing.JOptionPane.showMessageDialog(this, "Departamento actualizado");
                limpiarCamposDepartamento();
                BTNActualizar_Departamento.setEnabled(false);
                return;
            }
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Departamento no encontrado");

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar departamento: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNActualizar_DepartamentoActionPerformed

    private void BTNEliminarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliminarDepartamentoActionPerformed
   limpiarCamposDepartamento();
    jPanel3.setVisible(true);

    TXTIDDepartamento.setVisible(true);
    LBLIDDepartmento.setVisible(true); 

    TXTNombreDepartamento.setVisible(false);
    TXTSalarioBase.setVisible(false);
    LBLNombre.setVisible(false);
    LBLSalarioBase.setVisible(false);

    BTNEliminar_Departamento.setVisible(true);
    BTNEliminar_Departamento.setEnabled(false);

    BTNGuardarDepartamento.setVisible(false);
    BTNActualizar_Departamento.setVisible(false);

    BTNBuscarDepartamento.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNEliminarDepartamentoActionPerformed

    private void BTNEliminar_DepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliminar_DepartamentoActionPerformed
try {
        int id = Integer.parseInt(TXTIDDepartamento.getText());

        for (Departamento depto : departamentos) {
            if (depto.getIdDepartamento() == id) {
                departamentos.remove(depto);

                javax.swing.JOptionPane.showMessageDialog(this, "Departamento eliminado");
                limpiarCamposDepartamento();
                BTNEliminar_Departamento.setEnabled(false);
                return;
            }
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Departamento no encontrado");

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar departamento: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNEliminar_DepartamentoActionPerformed

    private void BTNBuscarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarDepartamentoActionPerformed
       if (BTNActualizar_Departamento.isVisible()) {
        buscarDepartamentoPorID();
    } else if (BTNEliminar_Departamento.isVisible()) {
        buscarDepartamentoParaEliminar();
    }  // TODO add your handling code here:
    }//GEN-LAST:event_BTNBuscarDepartamentoActionPerformed
private void limpiarCamposDepartamento() {
    TXTIDDepartamento.setText("");
    TXTNombreDepartamento.setText("");
    TXTSalarioBase.setText("");
}
private void verificarCamposDepartamento() {
    boolean completos = !TXTIDDepartamento.getText().isEmpty() &&
                        !TXTNombreDepartamento.getText().isEmpty() &&
                        !TXTSalarioBase.getText().isEmpty();

    BTNGuardarDepartamento.setEnabled(completos);
}
private void buscarDepartamentoPorID() {
    int id = Integer.parseInt(TXTIDDepartamento.getText());

    for (Departamento depto : departamentos) {
        if (depto.getIdDepartamento() == id) {
            // Mostrar los demás campos
            TXTNombreDepartamento.setVisible(true);
            TXTSalarioBase.setVisible(true);
            LBLNombre.setVisible(true);
            LBLSalarioBase.setVisible(true);

            // Cargar datos
            TXTNombreDepartamento.setText(depto.getNombre());
            TXTSalarioBase.setText(String.valueOf(depto.getSalarioBase()));

            // Habilitar botón actualizar
            BTNActualizar_Departamento.setEnabled(true);
            return;
        }
    }

    javax.swing.JOptionPane.showMessageDialog(this, "Departamento no encontrado");
}
private void buscarDepartamentoParaEliminar() {
    int id = Integer.parseInt(TXTIDDepartamento.getText());

    for (Departamento depto : departamentos) {
        if (depto.getIdDepartamento() == id) {
            // Mostrar los demás campos en modo lectura
            TXTNombreDepartamento.setVisible(true);
            TXTSalarioBase.setVisible(true);
            LBLNombre.setVisible(true);
            LBLSalarioBase.setVisible(true);

            TXTNombreDepartamento.setText(depto.getNombre());
            TXTSalarioBase.setText(String.valueOf(depto.getSalarioBase()));

            // Deshabilitar edición
            TXTNombreDepartamento.setEditable(false);
            TXTSalarioBase.setEditable(false);

            // Habilitar botón eliminar
            BTNEliminar_Departamento.setEnabled(true);
            return;
        }
    }

    javax.swing.JOptionPane.showMessageDialog(this, "Departamento no encontrado");
}

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNActualizarDepartamento;
    private javax.swing.JButton BTNActualizar_Departamento;
    private javax.swing.JButton BTNBuscarDepartamento;
    private javax.swing.JButton BTNCrearDepartamento;
    private javax.swing.JButton BTNEliminarDepartamento;
    private javax.swing.JButton BTNEliminar_Departamento;
    private javax.swing.JButton BTNGuardarDepartamento;
    private javax.swing.JLabel LBLDatosDepartamento;
    private javax.swing.JLabel LBLIDDepartmento;
    private javax.swing.JLabel LBLNombre;
    private javax.swing.JLabel LBLSalarioBase;
    private javax.swing.JTextField TXTIDDepartamento;
    private javax.swing.JTextField TXTNombreDepartamento;
    private javax.swing.JTextField TXTSalarioBase;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
