package com.mycompany.empleado;
import com.mycompany.empleado.EmpleadoPermanente;
import com.mycompany.empleado.EmpleadoTemporal;
import java.util.ArrayList;
import java.util.Date;
import com.mycompany.empleado.ReporteDesempeño;
import java.util.Calendar;
import javax.swing.ImageIcon;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Angely Nikol
 */
public class JRF_Interfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JRF_Interfaz.class.getName());

    /**
     * Creates new form JRF_Interfaz
     */
    public JRF_Interfaz() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        try {
                this.setIconImage(new ImageIcon(getClass().getResource("/main/java/commycompany/empleado/Imagen/Supermercado.png")).getImage());
        } catch (Exception e) {
 }


    
    }
    public void limpiarCampos(){

} 
    

    
    
    ArrayList<EmpleadoPermanente> empleadoP = new ArrayList<>();
    ArrayList<EmpleadoTemporal> empleadoT = new ArrayList<>();
    ArrayList<Departamento> departamentos = new ArrayList<>();
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        BTNGestionarEmpleados = new javax.swing.JButton();
        BTNGestionarDepartamentos = new javax.swing.JButton();
        BTNGenerarReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));

        jLabel12.setBackground(new java.awt.Color(51, 255, 51));
        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel12.setText("COMPUWORK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        BTNGestionarEmpleados.setText("Gestionar Empleados");
        BTNGestionarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGestionarEmpleadosActionPerformed(evt);
            }
        });

        BTNGestionarDepartamentos.setText("Gestionar Departamentos");
        BTNGestionarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGestionarDepartamentosActionPerformed(evt);
            }
        });

        BTNGenerarReporte.setText("Generar Reportes");
        BTNGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGenerarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(442, 442, 442)
                                .addComponent(BTNGestionarDepartamentos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(461, 461, 461)
                                .addComponent(BTNGenerarReporte)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(BTNGestionarEmpleados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(BTNGestionarEmpleados)
                .addGap(53, 53, 53)
                .addComponent(BTNGestionarDepartamentos)
                .addGap(54, 54, 54)
                .addComponent(BTNGenerarReporte)
                .addGap(314, 314, 314))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNGestionarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGestionarEmpleadosActionPerformed
    DatosEmpleado dialog = new DatosEmpleado(this, true);
    dialog.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNGestionarEmpleadosActionPerformed

    private void BTNGestionarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGestionarDepartamentosActionPerformed
    GestionDepartamentos dialog = new GestionDepartamentos(this, true);
    dialog.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNGestionarDepartamentosActionPerformed

    private void BTNGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGenerarReporteActionPerformed
    ReportesDesempeño dialog = new ReportesDesempeño(this, true, empleadoP, empleadoT, departamentos);
    dialog.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_BTNGenerarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JRF_Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNGenerarReporte;
    private javax.swing.JButton BTNGestionarDepartamentos;
    private javax.swing.JButton BTNGestionarEmpleados;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
