/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.empleado;

import java.util.Date;
import com.mycompany.empleado.EmpleadoPermanente;
import com.mycompany.empleado.EmpleadoTemporal;
import java.util.ArrayList;
import java.util.Date;
import com.mycompany.empleado.ReporteDesempeño;
import java.util.Calendar;
import javax.swing.ImageIcon;
/**
 *
 * @author Angely Nikol
 */
public class ReportesDesempeño extends javax.swing.JDialog {
    
     private ArrayList<EmpleadoPermanente> empleadoP;
    private ArrayList<EmpleadoTemporal> empleadoT;
    private ArrayList<Departamento> departamento;
    private final ArrayList<Departamento> departamentos;


  public ReportesDesempeño(java.awt.Frame parent, boolean modal,
                         ArrayList<EmpleadoPermanente> empleadoP,
                         ArrayList<EmpleadoTemporal> empleadoT,
                         ArrayList<Departamento> departamentos) {
    super(parent, modal);
    initComponents();
    this.setLocationRelativeTo(null);
    this.empleadoP = empleadoP;
    this.empleadoT = empleadoT;
    this.departamentos = departamentos;

   
    LBLReporteDepartamento.setVisible(false);
    TXTIDReporteDepartamento.setVisible(false);
    LBLReporte_Empleado.setVisible(false);
    TXTIDReporteEmpleado.setVisible(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LBLReporteEmpleado = new javax.swing.JLabel();
        JCNombreDepartamental = new javax.swing.JComboBox<>();
        LBLReporteDepartamento = new javax.swing.JLabel();
        LBLReporte_Empleado = new javax.swing.JLabel();
        BTNGenerarReporte = new javax.swing.JButton();
        TXTIDReporteDepartamento = new javax.swing.JTextField();
        TXTIDReporteEmpleado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        jLabel1.setText("Gestion de Reportes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(167, 167, 167))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        LBLReporteEmpleado.setText("Reporte Empleado");

        JCNombreDepartamental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ReporteDepartamental", "ReporteIndividual" }));
        JCNombreDepartamental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCNombreDepartamentalActionPerformed(evt);
            }
        });

        LBLReporteDepartamento.setText("ID Reporte Departamento");

        LBLReporte_Empleado.setText("ID Reporte Empleado");

        BTNGenerarReporte.setText("Generar");
        BTNGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGenerarReporteActionPerformed(evt);
            }
        });

        TXTIDReporteDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTIDReporteDepartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(LBLReporteEmpleado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBLReporte_Empleado)
                                    .addComponent(BTNGenerarReporte)
                                    .addComponent(LBLReporteDepartamento))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXTIDReporteDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(TXTIDReporteEmpleado)))
                            .addComponent(JCNombreDepartamental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LBLReporteEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JCNombreDepartamental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLReporteDepartamento)
                    .addComponent(TXTIDReporteDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTIDReporteEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLReporte_Empleado))
                .addGap(26, 26, 26)
                .addComponent(BTNGenerarReporte)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCNombreDepartamentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCNombreDepartamentalActionPerformed
    String indicetiporeporte=(String) JCNombreDepartamental.getSelectedItem();
    String ReporteDepartamental=(String)JCNombreDepartamental.getItemAt(0);
    String ReporteIndividual=(String)JCNombreDepartamental.getItemAt(1);
    
    if (indicetiporeporte==ReporteDepartamental) {
        LBLReporteDepartamento.setVisible(true);
        TXTIDReporteDepartamento.setVisible(true);
        
         LBLReporte_Empleado.setVisible(false);
        TXTIDReporteEmpleado.setVisible(false);
       
    } 
    else  {
        LBLReporteDepartamento.setVisible(false);
        TXTIDReporteDepartamento.setVisible(false);
         LBLReporte_Empleado.setVisible(true);
        TXTIDReporteEmpleado.setVisible(true);
       
    }        // TODO add your handling code here:
    }//GEN-LAST:event_JCNombreDepartamentalActionPerformed

    private void BTNGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGenerarReporteActionPerformed
      try {
            String tipo = (String) JCNombreDepartamental.getSelectedItem();
            
            if ("ReporteDepartamental".equals(tipo)) {
                // ✅ CORREGIDO: antes usabas TXTIDDepartamento (no existe aquí).
                // Ahora usamos TXTIDReporteDepartamento.
                int id = Integer.parseInt(TXTIDReporteDepartamento.getText());
                for (Departamento depto : departamentos) {
                    if (depto.getIdDepartamento() == id) {
                        depto.mostrarReporteDepartamento();
                        return;
                    }
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Departamento no encontrado");
            } else {
                int id = Integer.parseInt(TXTIDReporteEmpleado.getText());
                for (EmpleadoPermanente emp : empleadoP) {
                    if (emp.getIdEmpleado() == id) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                            "Reporte Empleado:\n" + emp.getNombre() + " " + emp.getApellido() +
                            "\nSalario: " + emp.calcularSalario());
                        return;
                    }
                }
                for (EmpleadoTemporal emp : empleadoT) {
                    if (emp.getIdEmpleado() == id) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                            "Reporte Empleado:\n" + emp.getNombre() + " " + emp.getApellido() +
                            "\nSalario: " + emp.calcularSalario());
                        return;
                    }
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Empleado no encontrado");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al generar reporte: " + e.getMessage());
        }
       
    }//GEN-LAST:event_BTNGenerarReporteActionPerformed

    private void TXTIDReporteDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTIDReporteDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTIDReporteDepartamentoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNGenerarReporte;
    private javax.swing.JComboBox<String> JCNombreDepartamental;
    private javax.swing.JLabel LBLReporteDepartamento;
    private javax.swing.JLabel LBLReporteEmpleado;
    private javax.swing.JLabel LBLReporte_Empleado;
    private javax.swing.JTextField TXTIDReporteDepartamento;
    private javax.swing.JTextField TXTIDReporteEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
